export const projects = [
  {
    id: 'training-log',
    name: 'Training Log',
    description: 'Track workouts and recoveries with charts, AI tagging, and quick logging.',
    status: 'Beta',
    href: 'https://training.oleksiyk.com',
    highlights: ['Workout timeline', 'Device sync', 'Shared plans'],
  },
  {
    id: 'dm-insights',
    name: 'Decision Map Insights',
    description: 'Surface insights from product discovery interviews and synthesize themes.',
    status: 'Alpha',
    href: 'https://dmi.oleksiyk.com',
    highlights: ['LLM clustering', 'Tag heatmaps', 'Research feed'],
  },
  {
    id: 'notespace',
    name: 'NoteSpace',
    description: 'Markdown-first notebook with audio snippets, tasks, and cross-app linking.',
    status: 'Concept',
    href: 'https://notes.oleksiyk.com',
    highlights: ['Backlink graphs', 'Quick capture', 'Shared spaces'],
  },
  {
    id: 'garden',
    name: 'Digital Garden',
    description: 'Public garden for essays, idea sketches, and knowledge handoffs.',
    status: 'Live',
    href: 'https://garden.oleksiyk.com',
    highlights: ['Custom typographic theme', 'Cross-link search', 'RSS feed'],
  },
  {
    id: 'ops-console',
    name: 'Ops Console',
    description: 'Internal dashboard to monitor Supabase metrics, edge logs, and jobs.',
    status: 'Private',
    href: 'https://ops.oleksiyk.com',
    highlights: ['Incident timelines', 'Job queue viewer', 'Access controls'],
  },
];
